# tailscale-github-wif
#
# Workload Identity Federation (WIF) trust between GitHub Actions and a tailnet.
# It is what lets a GitHub-hosted runner join the tailnet with NO long-lived
# Tailscale secret stored in GitHub:
#
#   workflow (permissions: id-token: write)
#     └─ requests a GitHub OIDC id-token for aud = <the Tailscale audience>
#          └─ tailscale/github-action@v4 POSTs it to Tailscale
#               └─ Tailscale validates iss + aud + sub + the claim rules below
#                    └─ returns a SHORT-LIVED API token with the scopes below
#                         └─ action mints an ephemeral auth key with those tags
#                              └─ runner joins the tailnet as an ephemeral node
#
# The only values GitHub has to hold are the federated identity's Client ID and
# its Audience — Tailscale documents both as NOT secrets ("These are not secrets
# and will be visible in the admin console"), so they are outputs here rather
# than secret-store items.
#   https://tailscale.com/docs/features/workload-identity-federation
#
# One `tailscale_federated_identity` per GitHub OWNER (org or user account), not
# per repository: a federated identity carries exactly ONE `subject` pattern and
# ONE pattern per custom claim, so per-repo scoping would mean one Tailscale
# trust credential per repo. Owner-level is the coarsest scope this module
# grants, and it is bounded by what the resulting token can actually do — the
# `federated_identity_scopes` and `federated_identity_tags` variables. Keep both
# minimal; see README.md for the threat model and the fork/PR analysis.
#
# Apply order (HUMAN-GATED): apply this component, read the outputs, then create
# the `TS_OAUTH_CLIENT_ID` and `TS_AUDIENCE` GitHub variables in each consuming
# repository. Nothing here creates GitHub-side configuration.
#
# Auth: the provider reads OAuth client credentials from the environment
#   TAILSCALE_OAUTH_CLIENT_ID / TAILSCALE_OAUTH_CLIENT_SECRET
# (never in code). That client needs only the `federated_keys` scope (write) —
# "read or modify federated identities and keys generated by federated
# identities", https://tailscale.com/kb/1623/.
#
# VERIFY THE CLIENT'S ACTUAL SCOPE before trusting that. A client provisioned
# with the console default carries scope `all` — full tailnet access, including
# ACL read/write and device management — and a leak of it is a whole-tailnet
# compromise rather than a CI-tag compromise. Read it back with
#   GET /api/v2/tailnet/-/keys?all=true
# rather than trusting any comment, including this one.

provider "tailscale" {
  # tailnet + credentials come from the environment (OAuth client). With an
  # OAuth client the tailnet defaults to that client's tailnet ("-").
}

# One federated identity per GitHub owner.
#
# `subject` is REQUIRED by the provider and is matched against the OIDC `sub`
# claim. GitHub's default `sub` is `repo:<owner>/<repo>:ref:refs/heads/<branch>`
# for branch pushes and `repo:<owner>/<repo>:pull_request` for pull requests —
# BUT repositories created (or renamed/transferred) after 2026-07-15 use the
# immutable form `repo:<owner>@<owner_id>/<repo>@<repo_id>:...`. A pattern of
# `repo:<owner>/*` silently stops matching those. So the default pattern is
# `repo:<owner>*`, which covers both shapes, and the ACTUAL authorization gate
# is the exact `repository_owner` + `repository_owner_id` claim rules below —
# `repository_owner_id` is immutable, so a renamed/typosquatted owner cannot
# slip past the deliberately loose subject prefix.
#   https://docs.github.com/en/actions/reference/security/oidc
#   https://github.blog/changelog/2026-04-23-immutable-subject-claims-for-github-actions-oidc-tokens/
resource "tailscale_federated_identity" "github_actions" {
  for_each = var.github_owners

  description = "GitHub Actions ${each.key}"
  issuer      = var.github_oidc_issuer
  scopes      = var.federated_identity_scopes
  tags        = var.federated_identity_tags
  subject     = coalesce(each.value.subject, "repo:${each.key}*")

  # `sub`, `iss` and `aud` are REJECTED here by the provider (reserved — they
  # have dedicated fields). Everything else is a free-form claim pattern where
  # `*` matches any run of characters and every other character must match
  # exactly.
  custom_claim_rules = merge(
    {
      repository_owner    = each.key
      repository_owner_id = each.value.owner_id
    },
    # Optional ref pin. Leaving it unset is a DELIBERATE trade-off: pinning
    # `refs/heads/main` breaks pull-request runs, whose `ref` claim is
    # `refs/pull/<n>/merge`. See README.md § "Ref restrictions".
    each.value.ref == null ? {} : { ref = each.value.ref },
  )

  # Audience is intentionally left unset so Tailscale generates it
  # (`api.tailscale.com/<client ID>`). Do not hand-pick one: the generated value
  # is bound to the client ID, which makes a token minted for one federated
  # identity useless against another.
}
