# Both values below are documented by Tailscale as NOT secrets — "These are not
# secrets and will be visible in the admin console"
# (https://tailscale.com/docs/features/workload-identity-federation). They are
# the two pieces of configuration a consuming repository needs, and they go in
# as GitHub repo/org *variables*, not secrets.

output "federated_identity_client_ids" {
  description = "Per-owner federated identity Client ID. Set as the TS_OAUTH_CLIENT_ID repo variable in each consuming repository. (The provider exposes it as the resource's `id` — there is no separate `client_id` attribute.)"
  value       = { for owner, fi in tailscale_federated_identity.github_actions : owner => fi.id }
}

output "federated_identity_audiences" {
  description = "Per-owner audience GENERATED BY TAILSCALE at creation (`api.tailscale.com/<client ID>`). This is the value the workflow requests its GitHub OIDC token for, and the TS_AUDIENCE repo variable. It is not hand-picked and is not `tailscale` — read it from here."
  value       = { for owner, fi in tailscale_federated_identity.github_actions : owner => fi.audience }
}

output "federated_identity_subjects" {
  description = "Per-owner `sub` pattern actually in effect, including the defaulted `repo:<owner>*` form. Useful when debugging a rejected exchange."
  value       = { for owner, fi in tailscale_federated_identity.github_actions : owner => fi.subject }
}
